---
exclude: [README.md, .gitignore]
timezone: null
lsi: false
markdown: kramdown

### content configuration ###
title:       "Human-centered Explanation Evaluation"
keywords:    ""
description: "Tutorial on human-centered explanation evaluation for XAI at <a href='https://2022.naacl.org/' target='_blank'>NAACL 2022</a> in Seattle, Washington."
logo:     "img/logo.png"
favicon:     "img/favicon/favicon.ico"
touch_icon:  "img/favicon/apple-touch-icon.png"

collections:
  - pages_2022

theme: jekyll-theme-minimal
