# Site settings
title: "NAACL 22 Tutorial on Human-centered Evaluations of Explanations"
# email: "robustnlp-tutorial@googlegroups.com"
baseurl: ""
url: "xai-hcee.github.io"

navbar-links:
    Overview: "/#overview"
    Speakers: "/#speakers"
    References: "references"

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
